### ISSUE TITLE
Hide core success message if password was not updated in User Settings

### ISSUE THREAD

**Issue by DanielSiepmann** [spoonerWeb/be_secure_pw#4]
TYPO3 Core will display a "Password was updated." message if the password field was submitted via Post.
Even if the extension prevents the update of the password.

This message irritates the user as it tells him that password was updated, even if it's not updated.

**Comment by s-nunez** [comment]
I can confirm this issue still exists in TYPO3 v7.6.3

**Comment by spoonerWeb** [comment]
Fixed in 7.0.3
