### ISSUE TITLE
BE-User -> Password isn't cryptic after create

### ISSUE THREAD

**Issue by sarahhoppe** [spoonerWeb/be_secure_pw#5]
When I activate be_secure_pw and create a new BE-User the password in database isn't cryptic. After first Login it is changing to a salted password.
Version of TYPO3 is 7.6.x

**Comment by astridhaubold** [comment]
I can confirm the behaviour (TYPO3 7.6.4): Password is saved in DB as Plaintext. Not only at creation but at every saving action. \TYPO3\CMS\Saltedpasswords\Evaluation\BackendEvaluator seems not to be called any more.

**Comment by spoonerWeb** [comment]
Fixed in 7.0.3
